# Generated by Django 4.1.5 on 2023-01-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Header name')),
                ('about', models.TextField(verbose_name='Header about')),
                ('about1', models.TextField(verbose_name='Header about1')),
                ('about2', models.TextField(verbose_name='Header about2')),
                ('about3', models.TextField(verbose_name='Header about3')),
                ('about4', models.TextField(verbose_name='Header about4')),
                ('about5', models.TextField(verbose_name='Header about5')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
    ]
