# Generated by Django 4.1.5 on 2023-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Head name')),
                ('name1', models.CharField(max_length=50, verbose_name='Head name1')),
                ('about', models.TextField(verbose_name='Head about')),
            ],
            options={
                'verbose_name': 'Head',
                'verbose_name_plural': 'Heads',
            },
        ),
    ]
