# Generated by Django 4.1.5 on 2023-01-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HeadCarusel name')),
                ('name1', models.CharField(max_length=50, verbose_name='HeadCarusel name1')),
                ('about', models.TextField(verbose_name='HeadCarusel about')),
            ],
            options={
                'verbose_name': 'HeadCarusel',
                'verbose_name_plural': 'HeadCarusels',
            },
        ),
    ]
