# Generated by Django 4.1.5 on 2023-01-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_headcarusel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Slaq about')),
                ('about1', models.TextField(verbose_name='Slaq about1')),
            ],
            options={
                'verbose_name': 'Slaq',
                'verbose_name_plural': 'Slaqs',
            },
        ),
    ]
