# Generated by Django 4.1.5 on 2023-01-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaq',
            name='about1',
        ),
    ]
