# Generated by Django 4.1.5 on 2023-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_video_delete_slaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='img',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='media', verbose_name='Video video'),
        ),
    ]
