# Generated by Django 4.1.5 on 2023-01-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_video_img_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Menu name')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menues',
            },
        ),
    ]
