# Generated by Django 4.1.5 on 2023-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='MenuAbout name')),
                ('name1', models.CharField(max_length=30, verbose_name='MenuAbout name1')),
                ('about', models.TextField(verbose_name='MenuAbout about')),
                ('about1', models.TextField(verbose_name='MenuAbout about1')),
                ('about2', models.TextField(verbose_name='MenuAbout about2')),
                ('img', models.ImageField(upload_to='media', verbose_name='MenuAbout image')),
            ],
            options={
                'verbose_name': 'MenuAbout',
                'verbose_name_plural': 'MenuAbouts',
            },
        ),
    ]
