# Generated by Django 4.1.5 on 2023-01-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTwoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='EventTwoImage name')),
                ('about', models.TextField(verbose_name='EventTwoImage about')),
                ('img', models.ImageField(upload_to='media', verbose_name='EventTwoImage image')),
            ],
            options={
                'verbose_name': 'EventsTwoImage',
                'verbose_name_plural': 'EventsTwoImages',
            },
        ),
    ]
