# Generated by Django 4.1.5 on 2023-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_eventtwoimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='EventFoot name')),
                ('about', models.TextField(verbose_name='EventFoot about')),
                ('about1', models.TextField(verbose_name='EventFoot about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='EventFoot image')),
            ],
            options={
                'verbose_name': 'EventFoot',
                'verbose_name_plural': 'EventFoots',
            },
        ),
    ]
