# Generated by Django 4.1.5 on 2023-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_eventfoot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfoot',
            name='about1',
            field=models.TextField(blank=True, null=True, verbose_name='EventFoot about1'),
        ),
    ]
