# Generated by Django 4.1.5 on 2023-01-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_eventfoot_about1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeFoot name')),
                ('name1', models.CharField(max_length=50, verbose_name='HomeFoot name1')),
                ('name2', models.CharField(max_length=50, verbose_name='HomeFoot name2')),
                ('name3', models.CharField(max_length=50, verbose_name='HomeFoot name3')),
                ('name4', models.CharField(max_length=50, verbose_name='HomeFoot name4')),
                ('about', models.TextField(verbose_name='HomeFoot about')),
                ('about1', models.TextField(verbose_name='HomeFoot about1')),
                ('about2', models.TextField(verbose_name='HomeFoot about2')),
                ('about3', models.TextField(verbose_name='HomeFoot about3')),
                ('about4', models.TextField(verbose_name='HomeFoot about4')),
            ],
            options={
                'verbose_name': 'HomeFoot',
                'verbose_name_plural': 'HomeFoots',
            },
        ),
    ]
