# Generated by Django 4.1.5 on 2023-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_kitchen'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='KitchenBody name')),
                ('name1', models.CharField(max_length=70, verbose_name='KitchenBody name1')),
                ('name2', models.CharField(max_length=70, verbose_name='KitchenBody name2')),
                ('about', models.TextField(verbose_name='KitchenBody about')),
                ('about1', models.TextField(verbose_name='KitchenBody about1')),
            ],
            options={
                'verbose_name': 'KitchenBody',
                'verbose_name_plural': 'KitchenBodies',
            },
        ),
    ]
