# Generated by Django 4.1.5 on 2023-01-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TeamImage name')),
                ('about', models.TextField(verbose_name='TeamImage about')),
                ('img', models.ImageField(upload_to='media', verbose_name='TeamImage image')),
            ],
        ),
    ]
