# Generated by Django 4.1.5 on 2023-01-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_teamimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamimage',
            options={'verbose_name': 'TeamImage', 'verbose_name_plural': 'TeamImages'},
        ),
    ]
