# Generated by Django 4.1.5 on 2023-01-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Newsletter image'),
        ),
    ]
