# Generated by Django 4.1.5 on 2023-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_newsletter_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='StoryFoot name')),
                ('name1', models.CharField(max_length=50, verbose_name='StoryFoot name1')),
                ('name2', models.CharField(max_length=50, verbose_name='StoryFoot name2')),
                ('name3', models.CharField(max_length=50, verbose_name='StoryFoot name3')),
                ('name4', models.CharField(max_length=50, verbose_name='StoryFoot name4')),
                ('about', models.TextField(verbose_name='StoryFoot about')),
                ('about1', models.TextField(verbose_name='StoryFoot about1')),
                ('about2', models.TextField(verbose_name='StoryFoot about2')),
                ('about3', models.TextField(verbose_name='StoryFoot about3')),
                ('about4', models.TextField(verbose_name='StoryFoot about4')),
            ],
            options={
                'verbose_name': 'StoryFoot',
                'verbose_name_plural': 'StoryFoots',
            },
        ),
    ]
