# Generated by Django 4.1.5 on 2023-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_storyfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='MenuHeader name')),
                ('about', models.TextField(verbose_name='MenuHeader about')),
                ('about1', models.TextField(verbose_name='MenuHeader about1')),
                ('about2', models.TextField(verbose_name='MenuHeader about2')),
                ('about3', models.TextField(verbose_name='MenuHeader about3')),
                ('about4', models.TextField(verbose_name='MenuHeader about4')),
                ('about5', models.TextField(verbose_name='MenuHeader about5')),
            ],
            options={
                'verbose_name': 'MenuHeader',
                'verbose_name_plural': 'MenuHeaders',
            },
        ),
    ]
