# Generated by Django 4.1.5 on 2023-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_menuheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='MenuHead name')),
                ('about', models.TextField(verbose_name='MenuHead about')),
            ],
            options={
                'verbose_name': 'MenuHead',
                'verbose_name_plural': 'MenuHeads',
            },
        ),
    ]
