# Generated by Django 4.1.5 on 2023-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_menuhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Breakfast name')),
            ],
            options={
                'verbose_name': 'Breakfast',
                'verbose_name_plural': 'Breakfasts',
            },
        ),
    ]
