# Generated by Django 4.1.5 on 2023-01-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_breakfastimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastimage',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='BreakfastImage image'),
        ),
    ]
