# Generated by Django 4.1.5 on 2023-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_breakfastimage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Lunch name')),
            ],
            options={
                'verbose_name': 'Lunch',
                'verbose_name_plural': 'Lunchs',
            },
        ),
    ]
