# Generated by Django 4.1.5 on 2023-01-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_lunchimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchimage',
            options={'verbose_name': 'LunchImage', 'verbose_name_plural': 'LunchImages'},
        ),
    ]
