# Generated by Django 4.1.5 on 2023-01-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_lunchimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dinner name')),
            ],
            options={
                'verbose_name': 'Dinner',
                'verbose_name_plural': 'Dinners',
            },
        ),
    ]
