# Generated by Django 4.1.5 on 2023-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_menufoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='UpdateHeader name')),
                ('about', models.TextField(verbose_name='UpdateHeader about')),
                ('about1', models.TextField(verbose_name='UpdateHeader about1')),
                ('about2', models.TextField(verbose_name='UpdateHeader about2')),
                ('about3', models.TextField(verbose_name='UpdateHeader about3')),
                ('about4', models.TextField(verbose_name='UpdateHeader about4')),
                ('about5', models.TextField(verbose_name='UpdateHeader about5')),
            ],
            options={
                'verbose_name': 'UpdateHeader',
                'verbose_name_plural': 'UpdateHeaders',
            },
        ),
    ]
