# Generated by Django 4.1.5 on 2023-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_updateheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='UpdateHead name')),
                ('about', models.TextField(verbose_name='UpdateHead about')),
            ],
            options={
                'verbose_name': 'UpdateHead',
                'verbose_name_plural': 'UpdateHeads',
            },
        ),
    ]
