# Generated by Django 4.1.5 on 2023-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_updatehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='UpdateUpdate name')),
            ],
            options={
                'verbose_name': 'UpdateUpdate',
                'verbose_name_plural': 'UpdateUpdates',
            },
        ),
    ]
