# Generated by Django 4.1.5 on 2023-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NewImage name')),
                ('about', models.TextField(verbose_name='NewImage about')),
                ('about1', models.TextField(verbose_name='NewImage about1')),
                ('about2', models.TextField(verbose_name='NewImage about2')),
                ('img', models.ImageField(upload_to='media', verbose_name='NewImage image')),
            ],
            options={
                'verbose_name': 'NewImage',
                'verbose_name_plural': 'NewImages',
            },
        ),
    ]
