# Generated by Django 4.1.5 on 2023-01-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_newimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newimage',
            name='about2',
        ),
    ]
