# Generated by Django 4.1.5 on 2023-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_updatefoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatefoot',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='UpdateFoot name1'),
        ),
        migrations.AddField(
            model_name='updatefoot',
            name='name2',
            field=models.CharField(max_length=50, null=True, verbose_name='UpdateFoot name2'),
        ),
        migrations.AddField(
            model_name='updatefoot',
            name='name3',
            field=models.CharField(max_length=50, null=True, verbose_name='UpdateFoot name3'),
        ),
        migrations.AddField(
            model_name='updatefoot',
            name='name4',
            field=models.CharField(max_length=50, null=True, verbose_name='UpdateFoot name4'),
        ),
    ]
