# Generated by Django 4.1.5 on 2023-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_updatefoot_name1_updatefoot_name2_updatefoot_name3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ContactHeader name')),
                ('about', models.TextField(verbose_name='ContactHeader about')),
                ('about1', models.TextField(verbose_name='ContactHeader about1')),
                ('about2', models.TextField(verbose_name='ContactHeader about2')),
                ('about3', models.TextField(verbose_name='ContactHeader about3')),
                ('about4', models.TextField(verbose_name='ContactHeader about4')),
                ('about5', models.TextField(verbose_name='ContactHeader about5')),
            ],
            options={
                'verbose_name': 'ContactHeader',
                'verbose_name_plural': 'ContactHeaders',
            },
        ),
    ]
