# Generated by Django 4.1.5 on 2023-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_contactheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ContactHead name')),
                ('about', models.TextField(verbose_name='ContactHead about')),
            ],
            options={
                'verbose_name': 'ContactHead',
                'verbose_name_plural': 'ContactHeads',
            },
        ),
    ]
