# Generated by Django 4.1.5 on 2023-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='about',
            field=models.TextField(null=True, verbose_name='Message about'),
        ),
        migrations.AddField(
            model_name='message',
            name='about1',
            field=models.TextField(null=True, verbose_name='Message about1'),
        ),
        migrations.AddField(
            model_name='message',
            name='about2',
            field=models.TextField(null=True, verbose_name='Message about2'),
        ),
        migrations.AddField(
            model_name='message',
            name='about3',
            field=models.TextField(null=True, verbose_name='Message about3'),
        ),
        migrations.AddField(
            model_name='message',
            name='name1',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name1'),
        ),
        migrations.AddField(
            model_name='message',
            name='name2',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name2'),
        ),
        migrations.AddField(
            model_name='message',
            name='name3',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name3'),
        ),
        migrations.AddField(
            model_name='message',
            name='name4',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name4'),
        ),
        migrations.AddField(
            model_name='message',
            name='name5',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name5'),
        ),
        migrations.AddField(
            model_name='message',
            name='name6',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name6'),
        ),
        migrations.AddField(
            model_name='message',
            name='name7',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name7'),
        ),
        migrations.AddField(
            model_name='message',
            name='name8',
            field=models.CharField(max_length=50, null=True, verbose_name='Message name8'),
        ),
    ]
