# Generated by Django 4.1.5 on 2023-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_message_about_message_about1_message_about2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ContactFoot name')),
                ('name1', models.CharField(max_length=50, verbose_name='ContactFoot name1')),
                ('name2', models.CharField(max_length=50, verbose_name='ContactFoot name2')),
                ('name3', models.CharField(max_length=50, verbose_name='ContactFoot name3')),
                ('name4', models.CharField(max_length=50, verbose_name='ContactFoot name4')),
                ('about', models.TextField(verbose_name='ContactFoot about')),
                ('about1', models.TextField(verbose_name='ContactFoot about1')),
                ('about2', models.TextField(verbose_name='ContactFoot about2')),
                ('about3', models.TextField(verbose_name='ContactFoot about3')),
                ('about4', models.TextField(verbose_name='ContactFoot about4')),
            ],
            options={
                'verbose_name': 'ContactFoot',
                'verbose_name_plural': 'ContactFoots',
            },
        ),
    ]
