# Generated by Django 4.1.5 on 2023-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_contactfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRevers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeRevers name')),
                ('name1', models.CharField(max_length=50, verbose_name='HomeRevers name1')),
                ('about', models.TextField(verbose_name='HomeRevers about')),
                ('about1', models.TextField(verbose_name='HomeRevers about1')),
                ('about2', models.TextField(verbose_name='HomeRevers about2')),
                ('about3', models.TextField(verbose_name='HomeRevers about3')),
                ('about4', models.TextField(verbose_name='HomeRevers about4')),
                ('about5', models.TextField(verbose_name='HomeRevers about5')),
                ('about6', models.TextField(verbose_name='HomeRevers about6')),
            ],
            options={
                'verbose_name': 'HomeRevers',
                'verbose_name_plural': 'HomeReverses',
            },
        ),
    ]
