# Generated by Django 4.1.5 on 2023-01-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_menurevers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRevers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='UpdateRevers name')),
                ('name1', models.CharField(max_length=50, verbose_name='UpdateRevers name1')),
                ('about', models.TextField(verbose_name='UpdateRevers about')),
                ('about1', models.TextField(verbose_name='UpdateRevers about1')),
                ('about2', models.TextField(verbose_name='UpdateRevers about2')),
                ('about3', models.TextField(verbose_name='UpdateRevers about3')),
                ('about4', models.TextField(verbose_name='UpdateRevers about4')),
                ('about5', models.TextField(verbose_name='UpdateRevers about5')),
                ('about6', models.TextField(verbose_name='UpdateRevers about6')),
            ],
            options={
                'verbose_name': 'UpdateRevers',
                'verbose_name_plural': 'UpdateReverses',
            },
        ),
    ]
