# Generated by Django 4.1.5 on 2023-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_detailhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='DetailBody name')),
                ('name1', models.CharField(max_length=60, verbose_name='DetailBody name1')),
                ('about', models.TextField(verbose_name='DetailBody about')),
                ('about1', models.TextField(verbose_name='DetailBody about1')),
                ('about2', models.TextField(verbose_name='DetailBody about2')),
                ('about3', models.TextField(verbose_name='DetailBody about3')),
                ('about4', models.TextField(verbose_name='DetailBody about4')),
                ('about5', models.TextField(verbose_name='DetailBody about5')),
                ('about6', models.TextField(verbose_name='DetailBody about6')),
                ('img', models.ImageField(upload_to='media', verbose_name='DetailBody image')),
            ],
            options={
                'verbose_name': 'DetailBody',
                'verbose_name_plural': 'DetailBodies',
            },
        ),
    ]
