# Generated by Django 4.1.5 on 2023-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_detailfoot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRevers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='DetailRevers name')),
                ('name1', models.CharField(max_length=50, verbose_name='DetailRevers name1')),
                ('about', models.TextField(verbose_name='DetailRevers about')),
                ('about1', models.TextField(verbose_name='DetailRevers about1')),
                ('about2', models.TextField(verbose_name='DetailRevers about2')),
                ('about3', models.TextField(verbose_name='DetailRevers about3')),
                ('about4', models.TextField(verbose_name='DetailRevers about4')),
                ('about5', models.TextField(verbose_name='DetailRevers about5')),
                ('about6', models.TextField(verbose_name='DetailRevers about6')),
            ],
            options={
                'verbose_name': 'DetailRevers',
                'verbose_name_plural': 'DetailReverses',
            },
        ),
    ]
