from django.contrib import admin
from .models import Header, Head, HeadCarusel, Video, Menu, MenuAbout, Event, EventTwoImage, EventFoot, HomeFoot, HomeRevers, StoryHeader, Kitchen, KitchenBody, Team, TeamImage, Newsletter, StoryFoot, StoryRevers, MenuHeader, MenuHead, Breakfast, BreakfastImage, Lunch, LunchImage, Dinner, DinnerImage, MenuFoot, MenuRevers, UpdateHeader, UpdateHead, UpdatUpdate, UpdateImage, New, NewImage, UpdateFoot, UpdateRevers, ContactHeader, ContactHead, Message, ContactFoot, ContactRevers, DetailHeader, DetailHead, DetailBody, DetailComment, DetailNew, DetailNewImage, DetailNewsletter, DetailFoot, DetailRevers

# Register your models here.

admin.site.register(Header)
admin.site.register(Head)
admin.site.register(HeadCarusel)
admin.site.register(Video)
admin.site.register(Menu)
admin.site.register(MenuAbout)
admin.site.register(Event)
admin.site.register(EventTwoImage)
admin.site.register(EventFoot)
admin.site.register(HomeFoot)
admin.site.register(HomeRevers)
admin.site.register(StoryHeader)
admin.site.register(Kitchen)
admin.site.register(KitchenBody)
admin.site.register(Team)
admin.site.register(TeamImage)
admin.site.register(Newsletter)
admin.site.register(StoryFoot)
admin.site.register(StoryRevers)
admin.site.register(MenuHeader)
admin.site.register(MenuHead)
admin.site.register(Breakfast)
admin.site.register(BreakfastImage)
admin.site.register(Lunch)
admin.site.register(LunchImage)
admin.site.register(Dinner)
admin.site.register(DinnerImage)
admin.site.register(MenuFoot)
admin.site.register(MenuRevers)
admin.site.register(UpdateHeader)
admin.site.register(UpdateHead)
admin.site.register(UpdatUpdate)
admin.site.register(UpdateImage)
admin.site.register(New)
admin.site.register(NewImage)
admin.site.register(UpdateFoot)
admin.site.register(UpdateRevers)
admin.site.register(ContactHeader)
admin.site.register(ContactHead)
admin.site.register(Message)
admin.site.register(ContactFoot)
admin.site.register(ContactRevers)
admin.site.register(DetailHeader)
admin.site.register(DetailHead)
admin.site.register(DetailBody)
admin.site.register(DetailComment)
admin.site.register(DetailNew)
admin.site.register(DetailNewImage)
admin.site.register(DetailNewsletter)
admin.site.register(DetailFoot)
admin.site.register(DetailRevers)
